name: unit_test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up MATLAB
      uses: matlab-actions/setup-matlab@v2

    - name: Run tests
      run: matlab -batch "cd Tests; run_all_tests;"

    - name: Install LaTeX
      run: sudo apt-get install -y texlive-latex-base texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra
      
    - name: Build PDF
      run: |
        # Your commands to generate PDF using latexmk
        # For example:
        latexmk -pdf -output-directory=unit_test/test1 unit_test/test1/test1.tex
